# Generated by Django 4.2.7 on 2026-04-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='eliminada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operador',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_doc',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='bienpatrimonial',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('MANTENIMIENTO', 'Mantenimiento'), ('INACTIVO', 'Inactivo'), ('BAJA', 'Baja')], default='ACTIVO', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='bienpatrimonial',
            name='origen',
            field=models.CharField(choices=[('COMPRA', 'Compra'), ('DONACION', 'Donación'), ('TRANSFERENCIA', 'Transferencia'), ('OMISION', 'Omisión')], default='COMPRA', max_length=15, verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('admin', 'Administrador'), ('operador', 'Operador'), ('supervisor', 'Supervisor')], default='empleado', max_length=10),
        ),
    ]
