# Generated by Django 4.2.7 on 2026-05-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tema_oscuro',
            field=models.BooleanField(default=False, verbose_name='Preferencia Modo Oscuro'),
        ),
    ]
