# Generated by Django 4.2.7 on 2026-04-24 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_bienpatrimonial_numero_compra_notificacion_eliminada_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivoCargaMasiva",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre_archivo", models.CharField(max_length=255)),
                ("hash_archivo", models.CharField(max_length=64, unique=True)),
                ("fecha_carga", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archivos_carga_masiva",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Archivo de carga masiva",
                "verbose_name_plural": "Archivos de carga masiva",
                "ordering": ["-fecha_carga"],
            },
        ),
        migrations.AddIndex(
            model_name="archivocargamasiva",
            index=models.Index(fields=["hash_archivo"], name="core_archiv_hash_ar_a2d9ef_idx"),
        ),
    ]
