# Generated by Django 4.2.7 on 2026-05-18 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_numero_compra_bien'),
    ]

    operations = [
        # LogActividad, ServicioExtra, Operador deletion, siem/fecha_registro/numero_compra
        # alterations are all handled by Branch A (0007, 0014, 0015). Only
        # PasswordResetToken is unique to this branch.
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'core_password_reset_token',
            },
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
