# Generated by Django 4.2.7 on 2026-04-27 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bienpatrimonial_numero_compra_notificacion_eliminada_and_more'),
    ]

    operations = [
    ]
