# Generated by Django 4.2.7 on 2026-04-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_numero_compra_bien'),
    ]

    operations = [
        migrations.AddField(
            model_name='bienpatrimonial',
            name='siem',
            field=models.DateField(blank=True, null=True, verbose_name='SIEM'),
        ),
    ]
