# Generated by Django 4.2.7 on 2026-05-26 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_logactividad_passwordresettoken_servicioextra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logactividad',
            name='bien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='core.bienpatrimonial'),
        ),
        migrations.AddField(
            model_name='logactividad',
            name='bien_clave_unica',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Clave Única del Bien'),
        ),
        migrations.AlterField(
            model_name='bienpatrimonial',
            name='origen',
            field=models.CharField(choices=[('COMPRA', 'Compra'), ('COMPRA_MENOR', 'Compra Menor'), ('DONACION', 'Donación'), ('TRANSFERENCIA', 'Transferencia'), ('OMISION', 'Omisión')], default='COMPRA', max_length=15, verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('empleado', 'Empleado Hospital'), ('operador', 'Operador')], default='empleado', max_length=10),
        ),
    ]
