# Generated by Django 4.2.7 on 2026-05-26 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_logactividad_passwordresettoken_servicioextra_and_more'),
        ('core', '0014_logactividad_remove_operador_usuario_and_more'),
    ]

    operations = [
        # AlterField for origen and tipo_usuario are handled by Branch A (0015).
        migrations.AddField(
            model_name='logactividad',
            name='bien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='core.bienpatrimonial'),
        ),
        migrations.AddField(
            model_name='logactividad',
            name='bien_clave_unica',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Clave Única del Bien'),
        ),
    ]
