# Generated by Django 4.2.7 on 2026-04-27 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20260427_1915'),
    ]

    operations = [
    ]
