# Generated by Django 4.2.7 on 2026-04-27 23:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import datetime
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bienpatrimonial_siem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operador',
            name='email',
        ),
        migrations.AddField(
            model_name='bienpatrimonial',
            name='descripcion_baja',
            field=models.TextField(blank=True, verbose_name='Descripción de baja'),
        ),
        migrations.AddField(
            model_name='bienpatrimonial',
            name='expediente_baja',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Expediente Baja'),
        ),
        migrations.AddField(
            model_name='bienpatrimonial',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Baja'),
        ),
        migrations.AddField(
            model_name='bienpatrimonial',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('core', 'BienPatrimonial').objects.filter(fecha_adquisicion__isnull=True).update(fecha_adquisicion=datetime.date.today())
        ),
        migrations.AlterField(
            model_name='bienpatrimonial',
            name='fecha_adquisicion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Alta'),
        ),
        migrations.AlterField(
            model_name='bienpatrimonial',
            name='servicios',
            field=models.CharField(blank=True, max_length=200, verbose_name='Servicios'),
        ),
        migrations.AlterField(
            model_name='bienpatrimonial',
            name='valor_adquisicion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio'),
        ),
        migrations.CreateModel(
            name='ArchivoCargaMasiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('hash_archivo', models.CharField(max_length=64, unique=True)),
                ('hash_contenido', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_carga_masiva', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo de carga masiva',
                'verbose_name_plural': 'Archivos de carga masiva',
                'ordering': ['-fecha_carga'],
                'indexes': [models.Index(fields=['hash_archivo'], name='core_archiv_hash_ar_bc62ff_idx')],
            },
        ),
    ]
