# Generated by Django 4.2.7 on 2026-04-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bienpatrimonial_siem_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienpatrimonial',
            name='numero_compra',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N° de Compra'),
        ),
    ]
