# Generated by Django 4.2.7 on 2026-06-29 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_origen_sin_especificar'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaMasivaUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_nombre', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total_filas_leidas', models.IntegerField(default=0)),
                ('total_filas_cargadas', models.IntegerField(default=0)),
                ('total_filas_omitidas', models.IntegerField(default=0)),
                ('columnas_no_reconocidas', models.JSONField(default=list)),
                ('warnings', models.JSONField(default=list)),
                ('resumen', models.JSONField(default=dict)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas_masivas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carga masiva (upload)',
                'verbose_name_plural': 'Cargas masivas (uploads)',
                'ordering': ['-fecha'],
            },
        ),
    ]
