# Generated by Django 4.2.7 on 2026-05-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_bienpatrimonial_numero_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre del servicio')),
            ],
            options={
                'verbose_name': 'Servicio Extra',
                'verbose_name_plural': 'Servicios Extra',
                'ordering': ['nombre'],
            },
        ),
    ]
