# Generated by Django 4.2.7 on 2026-05-07 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_servicioextra'),
    ]

    operations = [
    ]
