# Generated by Django 4.2.7 on 2026-07-17 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cargamasivaupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargamasivaupload',
            name='archivo_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.CreateModel(
            name='CargaMasivaPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_nombre', models.CharField(max_length=255)),
                ('archivo_hash', models.CharField(max_length=64)),
                ('filas_nuevas', models.JSONField(default=list)),
                ('filas_duplicadas', models.JSONField(default=list)),
                ('columnas_no_reconocidas', models.JSONField(default=list)),
                ('warnings', models.JSONField(default=list)),
                ('meta', models.JSONField(default=dict)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_pendientes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carga masiva pendiente',
                'verbose_name_plural': 'Cargas masivas pendientes',
                'ordering': ['-creado'],
            },
        ),
    ]
