# Generated by Django 4.2.7 on 2026-05-09 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20260507_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienpatrimonial',
            name='numero_compra',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N° de Compra'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('empleado', 'Empleado Hospital'), ('operador', 'Operador'), ('supervisor', 'Supervisor')], default='empleado', max_length=10),
        ),
        migrations.CreateModel(
            name='EmpleadoHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('legajo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('cargo', models.CharField(choices=[('ADMIN', 'Administrativo'), ('MEDICO', 'Médico'), ('ENFERMERIA', 'Enfermería'), ('TECNICO', 'Técnico'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('sector', models.CharField(blank=True, max_length=120)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado Hospital',
                'verbose_name_plural': 'Empleados Hospital',
                'ordering': ['apellido', 'nombre'],
                'indexes': [models.Index(fields=['dni'], name='core_emplea_dni_d5fdcb_idx'), models.Index(fields=['legajo'], name='core_emplea_legajo_397a46_idx'), models.Index(fields=['estado'], name='core_emplea_estado_21c99c_idx'), models.Index(fields=['cargo'], name='core_emplea_cargo_8cd1de_idx')],
            },
        ),
    ]
