# Generated by Django 4.2.7 on 2026-05-15 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_numero_compra_bien'),
        ('core', '0009_alter_bienpatrimonial_numero_compra_and_more'),
    ]

    operations = [
    ]
