# Generated by Django 4.2.7 on 2026-05-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_20260515_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienpatrimonial',
            name='numero_compra',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N° de Compra'),
        ),
        migrations.AlterField(
            model_name='bienpatrimonial',
            name='siem',
            field=models.BooleanField(default=False, verbose_name='SIEM'),
        ),
    ]
