# Generated by Django 4.2.7 on 2026-05-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_siem_booleanfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienpatrimonial',
            name='siem',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='SIEM'),
        ),
    ]
