# Generated by Django 4.2.7 on 2026-05-17 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_usuario_numero_doc_primary_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de Sesión'), ('CARGA', 'Carga de Bien'), ('CARGA_MASIVA', 'Carga Masiva'), ('EDICION', 'Edición de Bien'), ('BAJA', 'Baja de Bien'), ('ELIMINACION', 'Eliminación Definitiva'), ('RESTABLECIMIENTO', 'Restablecimiento de Bien')], max_length=20, verbose_name='Acción')),
                ('mensaje', models.TextField(verbose_name='Mensaje/Detalle')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
            ],
            options={
                'verbose_name': 'Log de Actividad',
                'verbose_name_plural': 'Logs de Actividad',
                'ordering': ['-fecha'],
            },
        ),
        migrations.RemoveField(
            model_name='operador',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AddField(
            model_name='bienpatrimonial',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Registro en Sistema'),
        ),
        migrations.AlterField(
            model_name='bienpatrimonial',
            name='siem',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=2, null=True, verbose_name='SIEM'),
        ),
        migrations.DeleteModel(
            name='EmpleadoHospital',
        ),
        migrations.DeleteModel(
            name='Operador',
        ),
        migrations.AddField(
            model_name='logactividad',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
