# Generated by Django 4.2.7 on 2026-05-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_logactividad_remove_operador_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienpatrimonial',
            name='origen',
            field=models.CharField(choices=[('COMPRA', 'Compra'), ('COMPRA_MENOR', 'Compra Menor'), ('DONACION', 'Donación'), ('TRANSFERENCIA', 'Transferencia'), ('OMISION', 'Omisión')], default='COMPRA', max_length=15, verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero_doc',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('empleado', 'Empleado Hospital'), ('operador', 'Operador')], default='empleado', max_length=10),
        ),
    ]
