# Generated by Django 4.2.7 on 2026-05-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_logactividad_bien_logactividad_bien_clave_unica_and_more'),
        ('core', '0015_add_origen_compra_menor'),
    ]

    operations = [
    ]
